### ISSUE TITLE
Setup instructions 

### ISSUE THREAD

**Issue by Vladinuto** [IntroVirt/IntroVirt#2]
Good evening, 

I'm interested in running this tool in one of our KVM servers to test the System Call extraction features, but I'm not sure how to properly set it up or if there are any dependencies, etc. 

Would it be possible to have a quick setup guide made available?

Thanks in advance!

**Comment by srpape** [comment]
Hi, the repository setup is still a work in progress. I'm still working on getting all of the components up to Github, notably the patched KVM module. You'll have to check back later.

**Comment by Vladinuto** [comment]
Thank you again for releasing this repository. Is there any active chat/message board/etc available for general questions or to provide support while the rest of the repo is being uploaded? Thanks im advance!

**Comment by Sidneys1** [comment]
The KVM patch is now available here: https://github.com/IntroVirt/kvm-introvirt

**Comment by laplante-sean** [comment]
Setup instructions should be pretty decent now. Feel free to re-open with a comment if more clarity is needed to get setup with the latest version.
